### ISSUE TITLE
[BUG] Kaggle ad challenge dataset no longer available for download (python interface demo notebook)

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA-Merlin/HugeCTR#201]
**Describe the bug**
For the Python interface demo notebook:
https://github.com/NVIDIA/HugeCTR/blob/master/notebooks/python_interface.ipynb

Dataset is no longer available from
https://s3-eu-west-1.amazonaws.com/kaggle-display-advertising-challenge-dataset/dac.tar.gz

Not sure if this is permanent, or temporary.

If permanent, we should be switching to using another dataset.

**To Reproduce**
1. How to build including `docker pull & docker run` commands
2. How to run including the JSON config file used

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu xx.yy]
 - Graphic card: [e.g. a single NVIDIA V100 or NVIDIA DGX A100]
 - CUDA version: [e.g. CUDA 11.x]
 - Docker image

**Additional context**

**Comment by vinhngx** [comment]
I found a cached version at https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/10082655/dac.tar.gz but I don't think we should use this.

The Criteo download page  https://labs.criteo.com/2014/02/kaggle-display-advertising-challenge-dataset/ also points to the dead link https://s3-eu-west-1.amazonaws.com/kaggle-display-advertising-challenge-dataset/dac.tar.gz

**Comment by serser** [comment]
@vinhngx I found criteo has updated a new dataset here https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/ , whose file structure is the same. I can use the same preprocessing script.

**Comment by zehuanw** [comment]
Thank you for the feedback, https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/ is Terabyte dataset which is different from the Kaggle dataset (but with the same format and same number of features). the broken link (https://s3-eu-west-1.amazonaws.com/kaggle-display-advertising-challenge-dataset/dac.tar.gz) seems not intended because the https://labs.criteo.com/2014/02/download-kaggle-display-advertising-challenge-dataset/ is still there. I cannot find any way to contact with them, but we may want to wait for few days and see if it can be fixed itself. 

If it cannot be fixed in short term we will consider to find some other ways to solve it. Then using one or two days log from Terabyte dataset seems to be a good choice.

**Comment by oddskool** [comment]
hey @zehuanw 
the updated link to download all Criteo datasets is here: https://ailab.criteo.com/ressources/
HTH

**Comment by zehuanw** [comment]
Thank you @oddskool , That's super helpful!

**Comment by zehuanw** [comment]
We have replaced all the samples with https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/  and https://ailab.criteo.com/ressources/ on master branch please check the fix. THX!

**Comment by oddskool** [comment]
http://go.criteo.net/criteo-research-kaggle-display-advertising-challenge-dataset.tar.gz is the url to use to access the Kaggle dataset
