### ISSUE TITLE
What is the algorithm of calculating frequent embedding counting threshold?

### ISSUE THREAD

**Issue by xyyaman** [NVIDIA-Merlin/HugeCTR#228]
Hi,

I was confused of the algorithm which calculates frequent embedding counting threshold in V3.1 such as:
`p_duplication(category) \approx 1/2 M (M-1) \left( \frac{count}{batch_size x num_iterations} \right)^2`.
Why is it calculated like this？

Also, I was confused of the word "duplication". For a data sample, it has 26 categories. Is 26 categories of two samples are the same called duplication, or >=1 categories of two samples are the same called duplication? Does "count_threshold" refer to count of samples or count of categories? If it means the category count, why cannot find the 26 categories in this threshold counting formula?

Hope to get some idea of these to learn better about this interesting HybridEmbedding way. Thanks.

**Comment by dgabel** [comment]
The reason for doing it this way is that the optimal threshold for the number of frequent categories is when there are practically no duplications occurring in the samples for the infrequent embedding. Therefore we set the duplication probability of a single category to a small number and calculate the corresponding count threshold. If a single category occurs in two samples or more within a gpu batch it is duplicated, with `M` the gpu-batch size. The expression above can be obtained by calculating one minus the chance the category doesn't occur or that it occurs once up to second order in the a-priori chance ` p=count / (batch_size x num_iterations)`. Since we are looking at small `p` for the threshold the second order should be fairly accurate evaluation of this quantity. This expression now allows us to calculate the `count` when a duplication probability threshold is given.

**Comment by zehuanw** [comment]
Hi @xyyaman , we are closing this issue. If @dgabel 's answer doesn't answer your question please reopen it. Thank you for your feedback again!
