### ISSUE TITLE
How can i build  HugeCTR without docker

### ISSUE THREAD

**Issue by ng-fukgin** [NVIDIA-Merlin/HugeCTR#263]
When i build HugeCTR follow this [doces.(Build HugeCTR from Source)](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/docs/hugectr_contributor_guide.md#build-hugectr-from-source) I found that docker have some problem on my super computer when i run the docker image(nvcr.io/nvidia/merlin/merlin-training:21.09) as follow 

> groups: cannot find name for group ID 1007
I have no name!@56a762eae3f8:/hugectr

so i want to build the HugeCTR without docker .how can i do

**Comment by ng-fukgin** [comment]
> my username in DGX is dgxuser4
> 
> > $id dgxuser4
> > uid=1005(dgxuser4) gid=1007(dgxuser4) groups=1007(dgxuser4),999(docker),1010(data),1013(ms161)

**Comment by XiaoleiShi-NV** [comment]
As posted in [this thread](https://stackoverflow.com/questions/50658883/how-to-correctly-use-system-user-in-docker-container):
> This sort of error will happen when the uid/gid does not exist in the /etc/passwd or /etc/group file inside the container.

Many ways are provided in this thread to work around this issue, please check it.

HugeCTR requires complex dependencies as shown [here](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/tools/dockerfiles/support_matrix.md), if you want to build by yourself, please make sure you have all of these dependencies properly installed in your environment. **We suggest using the container because it warps all of the complexities for you.**

**Comment by ng-fukgin** [comment]
> One point to clarify before answering your question: _you don't need to build HugeCTR by yourself when using the Merlin train container (nvcr.io/nvidia/merlin/merlin-training:21.09) because all executables and libraries of HugeCTR are pre-installed._
> 
> For the message: `groups: cannot find name for group ID 1007`, as posted in [this thread](https://stackoverflow.com/questions/50658883/how-to-correctly-use-system-user-in-docker-container):
> 
> > This sort of error will happen when the uid/gid does not exist in the /etc/passwd or /etc/group file inside the container.
> 
> Many ways are provided in this thread to work around this issue, please check it.
> 
> HugeCTR requires complex dependencies as shown [here](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/tools/dockerfiles/support_matrix.md), if you want to build by yourself, please make sure you have all of these dependencies properly installed in your environment. **We suggest using the container because it warps all of the complexities for you.**

Thank you for your answer, it is very helpful to me
