### ISSUE TITLE
[BUG] sok produces nan under horovod

### ISSUE THREAD

**Issue by nrailgun** [NVIDIA-Merlin/HugeCTR#268]
**Describe the bug**
I followed the [dense demo](https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/sparse_operation_kit/documents/tutorials/DenseDemo) , and the loss is nan.

**To Reproduce**

follow the tutorial and run
```
horovodrun -np 2 python3 run_sok_horovod.py --data_filename_prefix="./data_" --global_batch_size=65536 --max_vocabulary_size_per_gpu=1024     --slot_num=100 --nnz_per_slot=10 --num_dense_layers=6 --embedding_vec_size=4 --optimizer="adam"
```

but it seems to be working well under tf strategy
```
mpiexec -n 2 --allow-run-as-root python3 run_sok_MultiWorker_mpi.py --data_filename="./data_" --global_batch_size=65536 --max_vocabulary_size_per_gpu=8192 --slot_num=100 --nnz_per_slot=10 --num_dense_layers=6 --embedding_vec_size=4 --data_splited=1 --optimizer="adam"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/14273895/142170654-9c14ed8b-dbb4-4b69-8366-0fc6de257286.png)

**Environment (please complete the following information):**
 - Graphic card: NVIDIA-SMI 460.73.01 / Tesla T4
 - cuda: 11.0
 - cudnn: 8.1.1
 - nccl: 2.11
 - tensorflow: 2.5 
 - horovod: 0.23

**Comment by Jianbing-D** [comment]
Thanks for your feedback, we will try to reproduce it and will come back to you when we figure out why.

**Comment by nrailgun** [comment]
> Thanks for your feedback, we will try to reproduce it and will come back to you when we figure out why.

I used master commit (3ec24e22bd06c68f52f454a391164cc7b59c2a6c).

**Comment by kunlunl** [comment]
Hello, do you use `python3 gen_data.py --global_batch_size=65536 --slot_num=100 --nnz_per_slot=10 --iter_num=30` (just like the command in ReadMe) to generate your dataset?
If you don't specify `--vocabulary_size` in gen_data.py, the default value of vocabulary size is **8192**, which means if you want to execute run_sok_horovod.py with **1** process (like you did in the screenshot), you need to change the --max_vocabulary_size from 1024 to 8192 or larger. 
The reason why tf strategy does not meet this problem is that the value of --max_vocabulary_size is already 8192 in ReadMe.
Please let me know if this doesn't solve your problem.

**Comment by nrailgun** [comment]
> Hello, do you use `python3 gen_data.py --global_batch_size=65536 --slot_num=100 --nnz_per_slot=10 --iter_num=30` (just like the command in ReadMe) to generate your dataset? If you don't specify `--vocabulary_size` in gen_data.py, the default value of vocabulary size is **8192**, which means if you want to execute run_sok_horovod.py with **1** process (like you did in the screenshot), you need to change the --max_vocabulary_size from 1024 to 8192 or larger. The reason why tf strategy does not meet this problem is that the value of --max_vocabulary_size is already 8192 in ReadMe. Please let me know if this doesn't solve your problem.

Problem solved if I change max vocabulary size to 8192. Thanks.
