### ISSUE TITLE
Does hugeCTR support of hot and cold data statistical analysis ？[Question]

### ISSUE THREAD

**Issue by Jackwin** [NVIDIA-Merlin/HugeCTR#299]
Hi folks，

I'm a newbie to the hugeCTR and try to use hugeCTR. But there is a question that whether it supports the cold and hot data analysis since the embedding table is usually quite huge and there should be some data being accessed frequently and some not? Suppose the feature was not included, how could we add this feature? Thanks ahead.

Regards,

**Comment by minseokl** [comment]
Hi @Jackwin

Regarding the statistical analysis to determine if a give category is hot (or frequently accessed) in an embedding table, unfortunately our embedding table doesn't support it yet. A user must know the cardinality of each feature or the total number of vocabulary size in advance. Then, when a new category or key is shown in your training dataset, it is dynamically inserted into the embedding table on device, based on its hash table. Because we also know that recommender system datasets tend to have the characteristics you mentioned, we are actively explore solutions to better exploit the characteristic. We will try to make it available soon. Please let me know if you have more questions.

Thanks,
Minseok

**Comment by Jackwin** [comment]
@minseokl Many thanks:)
