### ISSUE TITLE
Test failed when I input decimal

### ISSUE THREAD

**Issue by YijiaZhao** [NVIDIA-Merlin/HugeCTR#32]
Hi HugeCTR experts:
in master/test/utest/layers/fully_connected_layer_test.cpp
107：for (size_t i = 0; i < k * n; ++i) h_weight[i] = (float)(rand() % 100);
108：for (size_t i = 0; i < m * k; ++i) h_in[i] = (float)(rand() % 100);

when I use decimal：
107：for (size_t i = 0; i < k * n; ++i) h_weight[i] = (float)((rand() % 100) * 0.1);
108：for (size_t i = 0; i < m * k; ++i) h_in[i] = (float)((rand() % 100)* 0.1);
the test is failed,  the max_diff of CPU and GPU is  > 0.1 (for example: 0.3125), why?

**Comment by minseokl** [comment]
Hi @YijiaZhao I apologize for reaching out to you so late. in newer versions of HugeCTR, we refactored our test code to use more stable `test::GaussianDataSimulator` which is based on cuRAND, instead of using a set of `rand()`.  Thus, it should be problematic anymore. If you still encounter a problem or face another issue. please let us know. Thanks!
