### ISSUE TITLE
[Question]  embedding table size of criteo dataset

### ISSUE THREAD

**Issue by LarryZhangy** [NVIDIA-Merlin/HugeCTR#330]
how to calculate  embedding table size of criteo dataset ?
why the num of pass of criteo dataset is 10 but not 24? (https://nvidia-merlin.github.io/HugeCTR/master/hugectr_embedding_training_cache.html#check-your-dataset) 

thanks!

**Comment by jershi425** [comment]
Hi @LarryZhangy, thank you for your questions!

For the first question, we need the following parameters:
1. `#of unique keys` in the Criteo Dataset. Let's assume it is `200,000,000`.
2. `key size` you used during training: int64 or int32. Let's say you are using int64, that is `8 bytes`.
3. `embedding vector size` you used during training. Let's say it is `128`.
4. `Factor` which is the size multiplier determined by different optimizers. Let's say we are using Adam. Then it is `3`.

Given these parameters, we can calculate the embedding table size in GB:
- `Keys:` 200,000,000 * 8 bytes / (1024)^3 = 1.5 GB
- `Vectors & Optimizers:` 3 * 200,000,000 * 128 * 4 bytes / (1024)^3 = 286 GB
- `In total:` 1.5 + 286 = 287.5 GB

For the second question, because Embedding Training Cache is designed to solve the situation when you are not able to fit the embedding table of the whole dataset in your GPU memory, you are actually free to choose any `number of pass` you like as long as the embedding of each pass can fit in your GPU memory. Yes, 24 is a natural choice in this case because there are 24 days in the Criteo dataset. We use 10 in our test because we are just using the first 3 days of the whole Criteo dataset and want to utilize more of our GPU memory. So to answer your question, I would say both 10 and 24 is valid number depending on the size of your dataset and the way you train it.

Please let me know if you have any further question.

Regards,
Jerry

**Comment by LarryZhangy** [comment]
Hi @jershi425 ， thank you for your patient and detailed explanation!

Two new question :
1) Is there any way to calculate the actual unique keys of Criteo Dataset before train?
2) Is there a tool to spilit some day of the whole Criteo dataset to some pass?

**Comment by jershi425** [comment]
Hi @LarryZhangy ,

1. For now, the only way to get the exact number of unique keys from Criteo is reading all the data and count it. But to analyze your dataset and decide whether you need to split, you only need a rough number: just make sure that your embedding for each pass can be held in your GPU resource.

**Comment by LarryZhangy** [comment]
@jershi425 ,Thank you! I Know how to do next.
