### ISSUE TITLE
[Question] Why hybrid embedding is bound with async data reading?

### ISSUE THREAD

**Issue by regnnighe** [NVIDIA-Merlin/HugeCTR#357]
Hi HugeCTR team,

Currently I am doing a performance breakdown of DLRM, where I want to test out the performance of asynchronous data reader and hybrid embedding. However, I found that in HugeCTR, RawAsync type must be used together with the hybrid embedding feature.

I am wondering is there any reason for this? And is there any way to split them apart?

**Comment by shijieliu** [comment]
Hi @regnnighe , thanks for trying out HugeCTR.

The reason why hybrid embedding is bounded with raw async reader is because hybrid embedding needs to collect data statistics before training to identify frequent and infrequent embedding. Now we use a seperate datareader called init_datareader to achieve this and you can reference the [code](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/HugeCTR/src/pybind/add_input.cpp#L153) here. 

Right now there is no easy way to split them. I think you can follow the way and try to handle the init_datareader in other data reader type. 

Right now we are working to migrate hybrid embedding into next generation embedding called [embedding collection](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/notebooks/embedding_collection.ipynb) and we will remove the dependency between async datareader and hybrid embedding. The target time for the finish of the migration is 22.11.
