### ISSUE TITLE
[Question] Are Sharp and IB a must have for multi-node traning?

### ISSUE THREAD

**Issue by heroes999** [NVIDIA-Merlin/HugeCTR#400]
<img width="602" alt="1684746296993" src="https://github.com/NVIDIA-Merlin/HugeCTR/assets/13531432/99323c76-3771-43b2-a7ef-75d74dac8626">

According to introduction, IB and rdma are not necessary. But I find code dependency of sharp and IB if -DENABLE_MPI is opened.
e.g. https://github.com/NVIDIA-Merlin/HugeCTR/blob/v4.2/HugeCTR/include/collectives/ib_proxy.hpp#L19

What's more, sharp is also directed referenced by hugectr source code.

Are there any macros or switches to close IB/rdma/sharp when building hugectr from source? Or will there be runtime error if I don't have IB port/switches?

**Comment by kanghui0204** [comment]
Hi @heroes999 

the [code](https://github.com/NVIDIA-Merlin/HugeCTR/blob/v4.2/HugeCTR/include/collectives/ib_proxy.hpp#L19) what you quote is HugeCTR custimized coumminication code. 

**how to use** 
there are two switches to control use NCCL or HugeCTR custimized coumminication code.

the first one is allreduce , you can search `all_reduce_algo` in [here](https://nvidia-merlin.github.io/HugeCTR/main/api/python_interface.html#solver) ,when you want to use HugeCTR custimized coumminication code, you can set it to `AllReduceAlgo.OneShot` , remember this require you machine have IB and sharp, otherwise you can set it to `AllReduceAlgo.NCCL`. 

the second one is all2all,  you can search `communication_type` in [here](https://nvidia-merlin.github.io/HugeCTR/main/api/python_interface.html#hybridembeddingparam),when you want to use HugeCTR custimized coumminication code, you can set it to `CommunicationType.IB_NVLink_Hier` , remember this require you machine have IB or RoCE rdma network device, otherwise you can set it to `CommunicationType.IB_NVLink`,this one use the NCCL do all2all. 

**when raise error?**
If you want to use our custimized coumminication code and don't have the network device(rdma or sharp) , it will raise a error during runtime.

**how to install**
If you are worry about how to install (or how to config the dependency software), I suggest you install HugeCTR in our [image](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-hugectr/tags) , in the image , we install all the dependency software , and you can install easily.

**Comment by heroes999** [comment]
Thanks for reply.
I also find that hybrid embedding layer depends on IB&sharp, is this a customized design too? I guess it will raise error if I use hybrid embedding without related devices. Btw, the introduction guide doesn't mention it(https://nvidia-merlin.github.io/HugeCTR/v23.05.00/api/python_interface.html?highlight=hybrid%20embedding#hybridembeddingparam)

**Comment by kanghui0204** [comment]
I think is second case , only hybrid embedding can choose customized or NCCL . In other embedding type , only use NCCL .
