### ISSUE TITLE
[Question] A question towards HugeCTR::concurrent_unordered_map::get_insert

### ISSUE THREAD

**Issue by heroes999** [NVIDIA-Merlin/HugeCTR#402]
I'm studying hashtable implementation and find that it might hang in some condition theoriotically. However, although I can reproduce with a similar code snippet, I can't repduce when launching HugeCTR training. I guess there is "magic" trick behind the scenes.

https://github.com/NVIDIA-Merlin/HugeCTR/blob/main/HugeCTR/include/hashtable/cudf/concurrent_unordered_map.cuh#L642
It is clearly a branch divergence case. Line 649 depends on Line 644 to move on.
Assuming two threads in a same warp call this function with same key(this key doesn't exist in hashtable before) and the compiler compiles Line 648 ahead of Line 642, HugeCTR would hang theoriotically, but it seems not happening.

A small case which will hang on A100, cuda 11.7.
<img width="881" alt="1685070021585" src="https://github.com/NVIDIA-Merlin/HugeCTR/assets/13531432/bab7373f-2d9f-4d7a-8571-83087bbbb03d">

**Comment by shijieliu** [comment]
hi @heroes999 thanks for trying hugectr.

I believe the reason why hugectr's code can work well is because in hugectr we set the writing address as `volatile` so that the compilers make sure the writing can be viewed in other threads. For more detailed information, you can check [cuda programing guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#volatile-qualifier)

**Comment by heroes999** [comment]
Thanks for reply. @shijieliu 
But I think this case might relate to branch divergence -- all threads in a warp should execute the same instructions so that if Line649 is executed first, other threads in the same warp are inactive(sleep). Even with the volatile qualifier, I'm not sure it will do any help if the needed thread(to change existing_value) hangs.

**Comment by KingsleyLiu-NV** [comment]
@heroes999 Thanks for your questions.
With the volatile qualifier, your test case will not hang because the compiler can handle warp divergence from volatile variable properly. Saying thread16-31 is executed first, and it finds that `dst[tid%16] != src[tid%16]`, it will NOT loop back immediately. Instead, thread0-15 gets executed and sets the volatile variable then. After that, thread16-31 reloads the volatile variable and gets away from the loop. Without the volatile qualifier, this warp divergence can cause hanging because thread16~31 will loop back forever if it gets executed first.

 You can use `Nsight Compute`  to view the compiled instructions to understand this mechanism. 

```bash
#include <cuda_runtime.h>
#include <iostream>

__global__ void test_kernel(int *src, volatile int *dst) {
  int tid = threadIdx.x + blockIdx.x * blockDim.x;
  if (tid < 16) {
    dst[tid] = 0;
  } else {
    while (dst[tid%16] != src[tid%16]) {}
  }
}

int main() {
  int h_src[16] = {0};
  int h_dst[16] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
  int *d_src, *d_dst;
  cudaStream_t stream;
  cudaStreamCreateWithPriority(&stream, cudaStreamNonBlocking, 0);
  cudaMalloc((void**)&d_src, 16*sizeof(int));
  cudaMalloc((void**)&d_dst, 16*sizeof(int));
  cudaMemcpyAsync(d_src, h_src, 16 * sizeof(int), cudaMemcpyHostToDevice, stream);
  cudaMemcpyAsync(d_dst, h_dst, 16 * sizeof(int), cudaMemcpyHostToDevice, stream);
  test_kernel<<<1, 64, 0, stream>>>(d_src, d_dst);
  cudaDeviceSynchronize();
  cudaStreamDestroy(stream);
  cudaFree(d_dst);
  cudaFree(d_src);
  return 0;
}
```

**Comment by heroes999** [comment]
It still hangs both on A100/cuda 11.7 RTX3090/cuda 11.7，any additional compiler params should be added? @KingsleyLiu-NV

**Comment by KingsleyLiu-NV** [comment]
@heroes999 

I still cannot reproduce the hang on A100/cuda11.7, and the order of conditional branch does not matter. Here are the code and log files:

[test_warp_divergence.cu.txt](https://github.com/NVIDIA-Merlin/HugeCTR/files/11620012/test_warp_divergence.cu.txt)
[test_warp_divergence.log](https://github.com/NVIDIA-Merlin/HugeCTR/files/11620006/test_warp_divergence.log)

Can you please do `cuobjdump -sass {YOUR_EXECUTABLE}` to check the instructions for your hanging case?

**Comment by heroes999** [comment]
Thanks @KingsleyLiu-NV, I've located the root cause - the default arch of nvcc is compute_52... which I assume is at least 70.
This case will no longer hang with compute capacity over 70.
